server:
  port: 80

mybatis:
  type-aliases-package: org.firespoon.fsbotserver.model
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: fsbotserver
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:fsbotdata.sqlite
    username:
    password:
